### PR TITLE
Add tome of knowledge

### LINKED ISSUE #21: [Suggestion]: Make Tome of Knowledge
you should really make tomb of knowledge like in the original projecte which unlocks all transmutation knowledge

### PR DESCRIPTION
**Pull request by OffsetMonkey538**
Fixes #21 

Still needed:
- [x] Testing
	- [x] Testing if it actually adds *all* items with EMC.
	- [x] Testing if it works on all supported Minecraft versions.
- [x] Translation of the item name
	- [x] ja_jp
	- [x] zh_cn

### CODE REVIEW

**Review by PTOM76 — APPROVED** [review]
it is working.
seems to be no problem.

**Comment by OffsetMonkey538** [comment]
Should be ready for merging

**Comment by OffsetMonkey538** [comment]
I added that check so the tome of knowledge wouldn't get consumed if you have already learned or unlearned all items.

**Comment by PTOM76** [comment]
it is worked in 1.18.2 and 1.20.1

**Comment by OffsetMonkey538** [comment]
Should be ready for merging

**Pull request merged**
